name: sultan
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.8
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  shared_preferences: ^2.0.12
  smooth_page_indicator: ^1.0.0+2
  keyboard_actions: ^4.0.1
  flutter_text_viewer: ^0.0.4
  carousel_slider: ^4.0.0
  flutter_screenutil: ^5.5.3+2
  table_calendar: ^3.0.5
  flutter_rating_bar: ^4.0.1
  gender_picker: ^1.1.0
  flutter_launcher_icons: ^0.9.3
  easy_localization: ^3.0.0
  badges: ^2.0.3
  never_behind_keyboard: ^1.0.1
  flutter_image_compress: ^1.1.0
  image_picker: ^0.8.5
  country_picker: ^2.0.15
  path: any
  path_provider: ^2.0.10
  flutter_swipe_action_cell: ^3.0.4
  flutter_widget_from_html: ^0.8.5
  open_file: ^3.2.1
  advance_pdf_viewer: any
  flutter_app_name: ^0.1.1
  syncfusion_flutter_datepicker: ^20.3.52
  swipeable_button_view: ^0.0.2
  flutter_phone_direct_caller: ^2.1.1
  flutter_datetime_picker: ^1.5.1
  permission_handler: ^9.2.0

  #firebase
  firebase_auth: ^3.11.1
  firebase_core: ^1.24.0
  firebase_messaging: ^11.4.1
  cloud_firestore: ^3.1.17

  #map
  google_maps_flutter: ^2.1.8
  location: ^4.4.0
  geocoding: ^2.0.4
  geolocator: ^9.0.2

dependency_overrides:
  image_picker_android: 0.8.4+13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter_app_name:
  name: "SULTAN"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appLogo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          style: italic